### ISSUE TITLE
Module not found: Can't resolve 'react-native-email-link' in '/Users/user/react-app

### ISSUE THREAD

**Issue by MikiahFender** [flexible-agency/react-native-email-link#99] opened 2022-01-21 15:45 UTC
Summary: can't import react native email link into our react native web project. 

Repo steps: 
- Create fresh react app. 
- yarn add react-native-email-link
- import into app.js
- yarn start

current results:
`Compiled with problems:X

ERROR in ./src/App.js 6:0-52

Module not found: Error: Can't resolve 'react-native-email-link' in '/Users/mf/Documents/dev/test-react-app/src' `

It looks like it's looking for the module in my current working directory and not node_modules. I see others are having the same problem with expo but we're using it only in react-native-web intended for web right now so thought I'd open a separate issue. 

We do have this working in our mobile repo that's also using react-native-web so I'm very confused.

**Comment by tschoffelen** [comment] 2022-02-08 10:42
Duplicate of #96, solved in #100

**Closed by tschoffelen** 2022-02-08 10:42 UTC
